### ISSUE TITLE
Error while agent stuck in 'remove togather'

### ISSUE THREAD

**Issue by canparlar** [rsverhagen94/TUD-Research-Project-2022#1]
On the line provided below when the object is removed, the object_id becomes None and there is no null check in the if statement. It should be like the commented if statement above, I think.

https://github.com/rsverhagen94/TUD-Research-Project-2022/blob/53d6f67abf2bf65ea185ff53fe8b4b8b134ac5cf/actions1/customActions.py#L309

**Comment by rsverhagen94** [comment]
Thanks for pointing this out. The issue should be resolved with the latest commit.
